exports.MySQLFields = [
   { Key: "id", Type: "INT", Extra: "NOT NULL AUTO_INCREMENT PRIMARY KEY"},
   { Key: "DataType", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Patient_Record_ID", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Patient_ID", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Name", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Phone_Number", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Address", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "DateOfRegistration", Type: "DATE", Extra: "NULL default NULL"},
   { Key: "HospitalArrivedAt", Type: "DATETIME", Extra: "NULL default NULL"},
   { Key: "Origin_Cluster", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Registered_Hospital", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Below_the_Poverty_Line", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Age", Type: "INT", Extra: "NULL default NULL"},
   { Key: "Female_Gender", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Prior_Diabetes", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Prior_HTN", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Prior_Dyslipidemia", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Active_Smoking", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Prior_PCI", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Prior_CABG", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Location_of_Infarct", Type: "INT", Extra: "NULL default NULL"},
   { Key: "First_heart_rate", Type: "INT", Extra: "NULL default NULL"},
   { Key: "Systolic_BP", Type: "INT", Extra: "NULL default NULL"},
   { Key: "Diastolic_BP", Type: "INT", Extra: "NULL default NULL"},
   { Key: "Radial_access_site", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Ambulance_transport", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Date_of_Symptom_Onset", Type: "DATE", Extra: "NULL default NULL"},
   { Key: "Time_of_Symptom_Onset", Type: "TIME", Extra: "NULL default NULL"},
   { Key: "Date_of_First_Medical_Contact", Type: "DATE", Extra: "NULL default NULL"},
   { Key: "Time_of_First_Medical_Contact", Type: "TIME", Extra: "NULL default NULL"},
   { Key: "Symptom_Onset_to_First_Medical_Contact", Type: "INT", Extra: "NULL default NULL"},
   { Key: "Date_of_First_ECG_with_STEMI", Type: "DATE", Extra: "NULL default NULL"},
   { Key: "Time_of_First_ECG_with_STEMI", Type: "TIME", Extra: "NULL default NULL"},
   { Key: "Total_NoOf_ECG", Type: "INT", Extra: "NULL default NULL"},
   { Key: "First_Asked_DateTime", Type: "DATETIME", Extra: "NULL default NULL"},
   { Key: "First_Replied_DateTime", Type: "DATETIME", Extra: "NULL default NULL"},
   { Key: "First_Medical_Contact_to_ECG", Type: "INT", Extra: "NULL default NULL"},
   { Key: "Date_of_First_STEMI_Network_Hospital", Type: "DATE", Extra: "NULL default NULL"},
   { Key: "Time_of_First_STEMI_Network_Hospital", Type: "TIME", Extra: "NULL default NULL"},
   { Key: "Date_of_AB_Hospital_Arrival", Type: "Date", Extra: "NULL default NULL"},
   { Key: "Time_of_AB_Hospital_Arrival", Type: "TIME", Extra: "NULL default NULL"},
   { Key: "Transfer_Time", Type: "INT", Extra: "NULL default NULL"},
   { Key: "External_Lysis", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Start_Date_of_Lytic_Therapy", Type: "DATE", Extra: "NULL default NULL"},
   { Key: "Start_Time_of_Lytic_Therapy", Type: "TIME", Extra: "NULL default NULL"},
   { Key: "Completion_Date_of_Lytic_Therapy", Type: "DATE", Extra: "NULL default NULL"},
   { Key: "Completion_Time_of_Lytic_Therapy", Type: "TIME", Extra: "NULL default NULL"},
   { Key: "ECG_to_Thrombolysis", Type: "INT", Extra: "NULL default NULL"},
   { Key: "Date_of_Coronary_Angiography_Start", Type: "DATE", Extra: "NULL default NULL"},
   { Key: "Time_of_Coronary_Angiography_Start", Type: "TIME", Extra: "NULL default NULL"},
   { Key: "Date_of_PCI_First_Balloon_Stent_Deployment", Type: "DATE", Extra: "NULL default NULL"},
   { Key: "Time_of_PCI_First_Balloon_Stent_Deployment", Type: "TIME", Extra: "NULL default NULL"},
   { Key: "Door_To_Needle_Time", Type: "INT", Extra: "NULL default NULL"},
   { Key: "Door_To_Balloon_Time", Type: "INT", Extra: "NULL default NULL"},
   { Key: "For_patients_getting_any_reperfusion_and_Total_Ischemic_Time", Type: "INT", Extra: "NULL default NULL"},
   { Key: "ECG_to_PCI", Type: "INT", Extra: "NULL default NULL"},
   { Key: "Thrombolysis_to_Angio", Type: "INT", Extra: "NULL default NULL"},
   { Key: "Thrombolysis_to_Angio_lessthan_24Hrs", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Thrombolysis_to_PCI", Type: "INT", Extra: "NULL default NULL"},
   { Key: "Thrombolysis_to_PCI_lessthan_24Hrs", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Date_of_Discharge", Type: "DATE", Extra: "NULL default NULL"},
   { Key: "No_Lytic_or_PCI", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Lytic", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Lytic_Agent", Type: "INT", Extra: "NULL default NULL"},
   { Key: "Coronary_Angiography", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "PCI", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Site_of_1st_medical_contact", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "AB_Hospital", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "C_Health_Care_Unit", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "D_Health_Care_Unit", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "E_Health_Care_Unit", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Admission_Aspirin", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Admission_Clopidogrel", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Admission_Heparin", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Admission_Prasugrel", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Admission_Ticagrelor", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Admission_Other", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Discharge_ABR_ACEI", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Discharge_Aspirin", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Discharge_Beta_blocker", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Discharge_Clopidogrel", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Discharge_Prasugrel", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Discharge_Statin", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Discharge_Ticagrelor", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "Discharge_Other", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "IHAE_Death", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "IHAE_Death_Remarks", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "IHAE_Stroke", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "IHAE_Hemorrhage", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "IHAE_Minor_Bleed", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "IHAE_Major_Bleed", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "IHAE_Cardiogenic_Shock", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "IHAE_Others", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "IHAE_Others_Remarks", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "One_Month_followup_Death", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "One_Month_Followup_Stroke", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "One_Year_followup_Death", Type: "TINYTEXT", Extra: "NOT NULL"},
   { Key: "One_Year_Followup_Stroke", Type: "TINYTEXT", Extra: "NOT NULL"},
];

exports.DateFields = [
   "DateOfRegistration",
   "Date_of_Symptom_Onset",
   "Date_of_First_Medical_Contact",
   "Date_of_First_ECG_with_STEMI",
   "Date_of_First_STEMI_Network_Hospital",
   "Date_of_AB_Hospital_Arrival",
   "Start_Date_of_Lytic_Therapy",
   "Completion_Date_of_Lytic_Therapy",
   "Date_of_Coronary_Angiography_Start",
   "Date_of_PCI_First_Balloon_Stent_Deployment",
   "Date_of_Discharge"
];
exports.TimeFields = [
   "Time_of_Symptom_Onset",
   "Time_of_First_Medical_Contact",
   "Time_of_First_ECG_with_STEMI",
   "Time_of_First_STEMI_Network_Hospital",
   "Time_of_AB_Hospital_Arrival",
   "Start_Time_of_Lytic_Therapy",
   "Completion_Time_of_Lytic_Therapy",
   "Time_of_Coronary_Angiography_Start",
   "Time_of_PCI_First_Balloon_Stent_Deployment"
];
exports.DateTimeFields = ["HospitalArrivedAt", "First_Asked_DateTime", "First_Replied_DateTime"];
exports.IntFields = [
   "Age",
   "Location_of_Infarct",
   "First_heart_rate",
   "Systolic_BP",
   "Diastolic_BP",
   "Symptom_Onset_to_First_Medical_Contact",
   "Total_NoOf_ECG",
   "First_Medical_Contact_to_ECG",
   "Transfer_Time",
   "ECG_to_Thrombolysis",
   "Door_To_Needle_Time",
   "Door_To_Balloon_Time",
   "For_patients_getting_any_reperfusion_and_Total_Ischemic_Time",
   "ECG_to_PCI",
   "Thrombolysis_to_Angio",
   "Thrombolysis_to_PCI",
   "Lytic_Agent"
];