exports.ReportFields = [
   "DataType",
   "Patient_Record_ID",
   "Patient_ID",
   "Name",
   "Phone Number",
   "Address",
   "DateOfRegistration",
	"Admission Type",
   "HospitalArrivedAt",
   "Origin Cluster",
   "Registered Hospital",
	"Referral Hospital",
	"Referral Hospital Arrival",
   "Age",
	"Female Gender",
	"Race",
	"Medical Insurance",
	"Location of Infarction",
	"Risk Factor - Diabetes",
	"Risk Factor - Hypertension",
	"Risk Factor - Smoking",
	"Risk Factor - Cholesterol",
	"Risk Factor - Family History",
   "Prior Diabetes",
	"HighCholesterol",
   "Prior HTN",
   "Active Smoking",
   "Prior PCI",
   "Prior CABG",
   "Radial access site",
   "Ambulance transport",
   "Date of Symptom Onset",
   "Time of Symptom Onset",
   "Date of First Medical Contact",
   "Time of First Medical Contact",
   "Symptom Onset to First Medical Contact",
   "Date of First ECG with STEMI",
   "Time of First ECG with STEMI",
   "Total No Of ECG",
   "First Medical Contact to ECG",
   "Date of First STEMI Network Hospital",
   "Time of First STEMI Network Hospital",
   "Date of Hub Hospital Arrival",
   "Time of Hub Hospital Arrival",
   "Transfer Time",
   "External Lysis (Y/N)",
   "Start Date of Lytic Therapy",
   "Start Time of Lytic Therapy",
   "Completion Date of Lytic Therapy",
   "Completion Time of Lytic Therapy",
   "ECG to Thrombolysis",
   "Date of Coronary Angiography Start",
   "Time of Coronary Angiography Start",
   "Date of PCI First Balloon/Stent Deployment",
   "Time of PCI First Balloon/Stent Deployment",
   "Door To Needle Time",
   "Door To Balloon Time(Primary PCI)",
   "For patients getting any reperfusion (no lytic or PCI = N), total ischemic time",
   "ECG to PCI",
   "Thrombolysis to Angio",
   "Thrombolysis to Angio > 24Hrs",
   "Thrombolysis to PCI",
   "Thrombolysis to PCI > 24Hrs",
   "Date of Discharge",
	"Missed STEMI",
   "Autoreperfused (Clinically diagnosed)",
   "Successful_Lysis",
   "No Lytic or PCI",
   "Lytic",
   "Lytic Agent",
   "Coronary_Angiography",
   "PCI",
	"Failed PCI",
	"Additional Revascularization Needed",
	"Type of PCI",
	"Culprit Vessel",
   "Site of 1st medical contact",
   "Hub Hospital",
   "S2 Health Care Unit",
   "S1 Health Care Unit",
   "E Health Care Unit(External STEMI Network)",
	"Admission Enoxaparin",
   "Admission Fondaparinux",
   "Admission - Aspirin",
   "Admission - Clopidogrel",
   "Admission - Heparin",
   "Admission - Prasugrel",
   "Admission - Ticagrelor",
   "Admission - Other",
   "Discharge - ABR/ACEI",
   "Discharge - Aspirin",
   "Discharge - Beta blocker",
   "Discharge - Clopidogrel",
   "Discharge - Prasugrel",
   "Discharge - Statin",
   "Discharge - Ticagrelor",
   "Discharge - Other",
   "IHAE-Death",
   "IHAE-Death Remarks",
   "IHAE-Stroke",
   "IHAE-Hemorrhage",
   "IHAE-Others",
   "IHAE-Others Remarks",
];



exports.ReportFieldKeys = [
   "DataType",
   "Patient_Record_ID",
   "Patient_ID",
   "Name",
   "Phone_Number",
   "Address",
   "DateOfRegistration",
	"Admission_Type",
   "HospitalArrivedAt",
   "Origin_Cluster",
   "Registered_Hospital",
	"Referral_Hospital",
	"Referral_Hospital_Arrival",
   "Age",
   "Female_Gender",
	"Race",
	"Medical_Insurance",
	"Location_of_Infarction",
	"Risk_Factor_Diabetes",
	"Risk_Factor_Hypertension",
	"Risk_Factor_Smoking",
	"Risk_Factor_Cholesterol",
	"Risk_Factor_Family_History",
   "Prior_Diabetes",
	"High_Cholesterol",
   "Prior_HTN",
   "Active_Smoking",
   "Prior_PCI",
   "Prior_CABG",
   "Radial_access_site",
   "Ambulance_transport",
   "Date_of_Symptom_Onset",
   "Time_of_Symptom_Onset",
   "Date_of_First_Medical_Contact",
   "Time_of_First_Medical_Contact",
   "Symptom_Onset_to_First_Medical_Contact",
   "Date_of_First_ECG_with_STEMI",
   "Time_of_First_ECG_with_STEMI",
   "Total_NoOf_ECG",
   "First_Medical_Contact_to_ECG",
   "Date_of_First_STEMI_Network_Hospital",
   "Time_of_First_STEMI_Network_Hospital",
   "Date_of_AB_Hospital_Arrival",
   "Time_of_AB_Hospital_Arrival",
   "Transfer_Time",
   "External_Lysis",
   "Start_Date_of_Lytic_Therapy",
   "Start_Time_of_Lytic_Therapy",
   "Completion_Date_of_Lytic_Therapy",
   "Completion_Time_of_Lytic_Therapy",
   "ECG_to_Thrombolysis",
   "Date_of_Coronary_Angiography_Start",
   "Time_of_Coronary_Angiography_Start",
   "Date_of_PCI_First_Balloon_Stent_Deployment",
   "Time_of_PCI_First_Balloon_Stent_Deployment",
   "Door_To_Needle_Time",
   "Door_To_Balloon_Time",
   "For_patients_getting_any_reperfusion_and_Total_Ischemic_Time",
   "ECG_to_PCI",
   "Thrombolysis_to_Angio",
   "Thrombolysis_to_Angio_lessthan_24Hrs",
   "Thrombolysis_to_PCI",
   "Thrombolysis_to_PCI_lessthan_24Hrs",
	"Date_of_Discharge",
	"MissedSTEMI",
   "Autoreperfused",
   "Successful_Lysis",
   "No_Lytic_or_PCI",
   "Lytic",
   "Lytic_Agent",
   "Coronary_Angiography",
   "PCI",
	"Failed_PCI",
	"Additional_Revascularization_Needed",
	"Type_of_PCI",
	"Culprit_Vessel",
   "Site_of_1st_medical_contact",
   "AB_Hospital",
   "C_Health_Care_Unit",
   "D_Health_Care_Unit",
   "E_Health_Care_Unit",
	"Admission_Enoxaparin",
   "Admission_Fondaparinux",
   "Admission_Aspirin",
   "Admission_Clopidogrel",
   "Admission_Heparin",
   "Admission_Prasugrel",
   "Admission_Ticagrelor",
   "Admission_Other",
   "Discharge_ABR_ACEI",
   "Discharge_Aspirin",
   "Discharge_Beta_blocker",
   "Discharge_Clopidogrel",
   "Discharge_Prasugrel",
   "Discharge_Statin",
   "Discharge_Ticagrelor",
   "Discharge_Other",
   "IHAE_Death",
   "IHAE_Death_Remarks",
   "IHAE_Stroke",
   "IHAE_Hemorrhage",
   "IHAE_Others",
   "IHAE_Others_Remarks"
];
